### ISSUE TITLE
google-cloud-datastore depends both on protobuf-java and protobuf-lite

### ISSUE THREAD

**Issue by sparhomenko** [GoogleCloudPlatform/google-cloud-java#2621]
Recent versions of `google-cloud-datastore` have transitive dependencies on both `com.google.protobuf:protobuf-lite:3.0.1` and `com.google.protobuf:protobuf-java:3.4.0`. These libraries contain incompatible classes with the same name, which for us intermittently causes `java.lang.NoSuchMethodError: com.google.protobuf.CodedOutputStream.isSerializationDeterministic()Z`.

This problem was fixed in the past by excluding `protobuf-lite` dependency, but it appeared again in 1.9.0. Here is the output of `gradle dependencyInsight`:
```
com.google.protobuf:protobuf-lite:3.0.1
\--- io.grpc:grpc-protobuf-lite:1.0.1
     +--- io.grpc:grpc-all:1.0.1
     |    \--- com.google.api.grpc:grpc-google-common-protos:0.1.0
     |         \--- com.google.cloud.datastore:datastore-v1-protos:1.3.0
     |              +--- com.google.cloud:google-cloud-datastore:1.10.0
     |              |    \--- runtime
     |              \--- com.google.cloud.datastore:datastore-v1-proto-client:1.4.1
     |                   \--- com.google.cloud:google-cloud-datastore:1.10.0 (*)
     \--- io.grpc:grpc-protobuf:1.0.1
          \--- io.grpc:grpc-all:1.0.1 (*)
```

From what I see this is caused by #2557 unintentionally reverting #2029 and downgrading `grpc-google-common-protos` to an old version (0.1.0) used by `datastore-v1-proto-client`. I understand the proper fix for that is GoogleCloudPlatform/google-cloud-datastore#170, but not sure about the timeline for that one. Would it be possible to upgrade `grpc-google-common-protos` back to a recent version?

**Comment by michaelbausor** [comment]
@garrettjonesgoogle Assigning you, since you also have https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2503. I can take this (or both issues) if necessary.

**Comment by garrettjonesgoogle** [comment]
Working on this - we will start generating datastore protos using the googleapis toolchain so that we don't get version conflicts.

**Comment by wsh** [comment]
I believe #2770 fixed this. :)

**Comment by hzyi-google** [comment]
Close the issue since it's fixed. Please reopen if there still is work to be done.
